### PR TITLE
Quick git-attributes file

### PR DESCRIPTION
**Pull request by KasperFranz**

### CODE REVIEW

**Review by edwardkarlsson — APPROVED** [review]

**Comment by edwardkarlsson** [comment]
Thanks! 👍

**Review by edwardkarlsson — CHANGES_REQUESTED** [review]
The .gitattributes in your PR is located in a demo/demo folder. Could you please update to the root of the project? Don't think it will have any effect in its current location. Thanks.

**Comment by KasperFranz** [comment]
Not sure how it went there, let me update that

**Comment by KasperFranz** [comment]
fixed

**Review by edwardkarlsson — APPROVED** [review]

**Pull request merged**
